/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.petservicosadminview.petservicosadminview.panel;

import br.com.petservicos.domain.GenericDomain;
import br.com.petservicosadminview.petservicosadminview.buttons.Alterar;
import br.com.petservicosadminview.petservicosadminview.buttons.Cancelar;
import br.com.petservicosadminview.petservicosadminview.buttons.Deletar;
import br.com.petservicosadminview.petservicosadminview.buttons.Incluir;
import br.com.petservicosadminview.petservicosadminview.buttons.Pesquisar;
import br.com.petservicosadminview.petservicosadminview.buttons.Salvar;
import br.com.petservicosadminview.petservicosadminview.enums.StatusTelaEnum;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lina
 * @param <T>
 */
public class BotoesCrud <T extends GenericDomain> extends javax.swing.JPanel {
    
    private final Pesquisar<T> pesquisar;
    private final Incluir<T> incluir;
    private final Salvar<T> salvar;
    private final Alterar<T> alterar;
    private final Deletar<T> deletar;
    private final Cancelar<T> cancelar;
    private StatusTelaEnum statusTelaEnum;
    public Pesquisar<T> getPesquisar() {
        return pesquisar;
    }
    
    
    /**
     * Creates new form BotoesCrud
     */
    public BotoesCrud() {
        statusTelaEnum= StatusTelaEnum.PESQUISAR;
        incluir = new Incluir<>(statusTelaEnum);
        salvar = new Salvar<>(statusTelaEnum);
        alterar = new Alterar<>(statusTelaEnum);
        deletar = new Deletar<>(statusTelaEnum);
        cancelar = new Cancelar<>(statusTelaEnum);
        pesquisar = new Pesquisar<>(statusTelaEnum);
        initComponents();
    }
    
    private void addActions(){
        pesquisar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
    }
    private void enabledButtons(){
        if(StatusTelaEnum.INCLUIR.equals(statusTelaEnum)||
                StatusTelaEnum.ALTERAR.equals(statusTelaEnum)){
            incluir.setEnabled(false);
            alterar.setEnabled(false);
            deletar.setEnabled(false);
            salvar.setEnabled(true);
        }else if(StatusTelaEnum.PESQUISAR.equals(statusTelaEnum)){
            incluir.setEnabled(true);
            alterar.setEnabled(false);
            deletar.setEnabled(false);
            salvar.setEnabled(false);
            
        }else if(StatusTelaEnum.PESQUISADO.equals(statusTelaEnum)){
            incluir.setEnabled(true);
            alterar.setEnabled(true);
            deletar.setEnabled(true);
            salvar.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = incluir;
        jButton2 = salvar;
        jButton3 = alterar;
        jButton4 = deletar;
        jButton5 = cancelar;

        setLayout(new java.awt.GridLayout(1, 5, 5, 0));
        add(jButton1);
        add(jButton2);
        add(jButton3);
        add(jButton4);
        add(jButton5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
